#pragma config(Motor,  port1,           motorFrontLeft, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motorFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorRearLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motorRearRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motorFunction1, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           motorFunction2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motorFunction3, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motorFunction4, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motorFunction5, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motorFunction6, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool isPressed(int button){
	bool state;
	if(button == 1){
		state = true;
		}else{
		state = false;
	}
	return state;
}
int sensorCalibrator(int sensor){
	int calibrationVal;
	//Code
	return calibrationVal;
}
int apiJoystickDrive(int joyStick, int maxSpeed, int throttle, int deadzone, bool isReversed){
	int x;
	if((joyStick / 128) < (throttle / 100)){
		if(abs(joyStick) > deadzone && isReversed){
			x = 0 - maxSpeed;
			}else if(abs(joyStick) > deadzone && isReversed == false){
			x = maxSpeed;
			}else{
			x = 0;
		}
		}else{
		if(abs(joyStick) > deadzone && isReversed){
			x = 0 - maxSpeed  * (throttle / 100);
			}else if(abs(joyStick) > deadzone && isReversed == false){
			x = maxSpeed * (throttle / 100);
			}else{
			x = 0;
		}
	}
	return x;
}
/*================================================================================================*/
void setMotorValSingleJoyDualMotor(int joyStickX1, int joyStickY1, int maxSpeed, int throttle, int deadzone, bool isReversed){
	motor[motorFrontLeft] = apiJoystickDrive(joyStickY1, maxSpeed, throttle, deadzone, isReversed) - apiJoystickDrive(joyStickX1, maxSpeed, throttle, deadzone, isReversed);
	motor[motorFrontRight] = apiJoystickDrive(joyStickY1, maxSpeed, throttle, deadzone, isReversed) + apiJoystickDrive(joyStickX1, maxSpeed, throttle, deadzone, isReversed);
}
void setMotorValDualJoyDualMotor(int joyStickY1, int joyStickX2, int maxSpeed, int throttle, int deadzone, bool isReversed){
	motor[motorFrontLeft] = apiJoystickDrive(joyStickY1, maxSpeed, throttle, deadzone, isReversed) - apiJoystickDrive(joyStickX2, maxSpeed, throttle, deadzone, isReversed);
	motor[motorFrontRight] = apiJoystickDrive(joyStickY1, maxSpeed, throttle, deadzone, isReversed) + apiJoystickDrive(joyStickX2, maxSpeed, throttle, deadzone, isReversed);
}
void setMotorValQuad(int joyStickX1, int joyStickY1, int joyStickX2, int joyStickY2, int maxSpeed, int throttle, int deadzone, bool isReversed){
	//Code
}
void setMotorOmnidrive(int joyStickX1, int joyStickY1, int joyStickX2, int joyStickY2, int maxSpeed, int throttle, int deadzone, bool isReversed){
	//Code
}
int buttonOpenClose(int button, int button1, int maxSpeed, bool isReversed){
	int motorValue;
	//Code
	return motorValue;
}
int setButtonHoldActivation(int button, int maxSpeed, bool isReversed){
	int motorValue;
	//Code
	return motorValue;
}
int motorTurnOnButtonPress(int button, int maxSpeed, bool isReversed){
	int motorValue;
	//Code
	return motorValue;
}

task main(){

	while(true){
		//Controller Commands Go Here.
	}
}
